version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: yaya_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: yaya
      POSTGRES_PASSWORD: yaya_password
      POSTGRES_DB: yaya_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yaya_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: yaya_frontend
  #   restart: unless-stopped
  #   env_file:
  #     - ./frontend/.env
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend

volumes:
  db_data:
